In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("sqlite:///../database/ecommerce.db")
print("Database Connected Successfully!")

Database Connected Successfully!

In [2]:
query = "SELECT * FROM ecommerce LIMIT 5;"

df = pd.read_sql(query, engine)

df

   product_id product_name     category    price  units_sold  rating in_stock
0           1       Camera  Electronics   391.46           8     4.5     True
1           2        Shoes      Fashion  1091.88         333     3.0     True
2           3     Backpack      Fashion   893.51         200     3.8     True
3           4        Watch      Fashion   162.30          87     5.0     True
4           5       Camera  Electronics  1378.94          43     1.5     True

# Business Question 1

## Top 5 Most Expensive Products

In [3]:
query = """
SELECT product_name,
       category,
       price
FROM ecommerce
ORDER BY price DESC
LIMIT 5;
"""

df = pd.read_sql(query, engine)

df

  product_name     category    price
0     Keyboard  Electronics  1499.04
1        Mouse  Electronics  1494.54
2        Mouse  Electronics  1493.27
3       Laptop  Electronics  1490.07
4        Mouse  Electronics  1488.28

# Business Question 2

## Category-wise Total Products

In [4]:
query = """
SELECT category,
       COUNT(*) AS total_products
FROM ecommerce
GROUP BY category;
"""

df = pd.read_sql(query, engine)

df

      category  total_products
0  Electronics             603
1      Fashion             397

# Business Question 3

## Average Price by Category

In [5]:
query = """
SELECT category,
       AVG(price) AS average_price
FROM ecommerce
GROUP BY category;
"""

df = pd.read_sql(query, engine)

df

      category  average_price
0  Electronics     787.672554
1      Fashion     715.502217

# Business Question 4

## Top 5 Highest Selling Products

In [6]:
query = """
SELECT product_name,
       units_sold
FROM ecommerce
ORDER BY units_sold DESC
LIMIT 5;
"""

df = pd.read_sql(query, engine)

df

  product_name  units_sold
0       Laptop         499
1      T-shirt         499
2        Mouse         499
3       Camera         498
4        Watch         497

# Business Question 5

## Top 5 Highest Rated Products

In [7]:
query = """
SELECT product_name,
       rating
FROM ecommerce
ORDER BY rating DESC
LIMIT 5;
"""

df = pd.read_sql(query, engine)

df

  product_name  rating
0        Watch     5.0
1       Camera     5.0
2     Keyboard     5.0
3   Headphones     5.0
4        Mouse     5.0

# Business Question 6

## Total Units Sold by Category

In [8]:
query = """
SELECT category,
       SUM(units_sold) AS total_units
FROM ecommerce
GROUP BY category;
"""

df = pd.read_sql(query, engine)

df

      category  total_units
0  Electronics       145696
1      Fashion       104816

# Business Question 7

## Products Out of Stock

In [9]:
query = """
SELECT product_name,
       category
FROM ecommerce
WHERE in_stock = 'False';
"""

df = pd.read_sql(query, engine)

df

    product_name     category
0         Camera  Electronics
1          Watch      Fashion
2        T-shirt      Fashion
3         Laptop  Electronics
4          Shoes      Fashion
..           ...          ...
192     Backpack      Fashion
193   Smartphone  Electronics
194     Backpack      Fashion
195     Backpack      Fashion
196     Backpack      Fashion

[197 rows x 2 columns]

# Business Question 8

## Products with Rating Greater Than 4

In [10]:
query = """
SELECT product_name,
       rating
FROM ecommerce
WHERE rating > 4;
"""

df = pd.read_sql(query, engine)

df

    product_name  rating
0         Camera     4.5
1          Watch     5.0
2          Watch     4.6
3     Smartphone     4.3
4        T-shirt     4.8
..           ...     ...
223     Backpack     4.6
224        Shoes     4.5
225   Smartphone     4.9
226        Shoes     4.2
227     Backpack     5.0

[228 rows x 2 columns]

# Business Question 9

## Highest Price by Category

In [11]:
query = """
SELECT category,
       MAX(price) AS highest_price
FROM ecommerce
GROUP BY category;
"""

df = pd.read_sql(query, engine)

df

      category  highest_price
0  Electronics        1499.04
1      Fashion        1487.30

# Business Question 10

## Total Revenue by Category

In [12]:
query = """
SELECT category,
       SUM(price * units_sold) AS total_revenue
FROM ecommerce
GROUP BY category;
"""

df = pd.read_sql(query, engine)

df

      category  total_revenue
0  Electronics   1.134817e+08
1      Fashion   7.568538e+07